/**
 * Export utilities - Excel and PDF
 * Uses ExcelJS for Excel exports (secure replacement for xlsx)
 */

import ExcelJS from 'exceljs';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExportData {
  company: {
    name: string;
    logo_url?: string;
  };
  client: {
    name: string;
    wedding_date: string;
  };
  guests: any[];
  hotels: any[];
  gifts: any[];
  transport?: any[];
  vendors: any[];
  budget: any[];
  events: any[];
  timeline: any[];
  documents: any[];
}

export async function exportToExcel(data: ExportData): Promise<ArrayBuffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'WeddingFlo';
  workbook.created = new Date();

  // Cover sheet
  const coverSheet = workbook.addWorksheet('Cover');
  coverSheet.addRow([data.company.name]);
  coverSheet.addRow([]);
  coverSheet.addRow([`Wedding: ${data.client.name}`]);
  coverSheet.addRow([`Date: ${new Date(data.client.wedding_date).toLocaleDateString()}`]);
  coverSheet.addRow([]);
  coverSheet.addRow(['Generated by WeddingFlo']);
  coverSheet.addRow([`Export Date: ${new Date().toLocaleString()}`]);

  // Style cover sheet
  coverSheet.getRow(1).font = { bold: true, size: 16 };
  coverSheet.getRow(3).font = { bold: true, size: 14 };

  // Guest List Sheet - Full round-trip compatible with import template
  if (data.guests.length > 0) {
    const guestSheet = workbook.addWorksheet('Guests');
    guestSheet.columns = [
      { header: 'ID (Do not modify)', key: 'id', width: 40 },
      { header: 'Name *', key: 'name', width: 25 },
      { header: 'Email', key: 'email', width: 28 },
      { header: 'Phone', key: 'phone', width: 18 },
      { header: 'Group', key: 'group', width: 18 },
      { header: 'Side', key: 'side', width: 15 },
      { header: 'RSVP Status', key: 'rsvp', width: 15 },
      { header: 'Party Size', key: 'partySize', width: 12 },
      { header: 'Additional Guest Names', key: 'additionalGuests', width: 35 },
      { header: 'Relationship to Family', key: 'relationship', width: 20 },
      { header: 'Attending Events', key: 'eventsAttending', width: 30 },
      { header: 'Arrival Date/Time', key: 'arrivalDatetime', width: 20 },
      { header: 'Arrival Mode', key: 'arrivalMode', width: 18 },
      { header: 'Departure Date/Time', key: 'departureDatetime', width: 20 },
      { header: 'Departure Mode', key: 'departureMode', width: 18 },
      { header: 'Meal Preference', key: 'mealPreference', width: 15 },
      { header: 'Dietary Restrictions', key: 'dietary', width: 25 },
      { header: 'Hotel Required (TRUE/FALSE)', key: 'hotelRequired', width: 15 },
      { header: 'Transport Required (TRUE/FALSE)', key: 'transportRequired', width: 18 },
      { header: 'Gift Required (TRUE/FALSE)', key: 'giftRequired', width: 15 },
      { header: 'Gift to Give', key: 'giftToGive', width: 25 },
      { header: 'Notes', key: 'notes', width: 40 },
      { header: 'Checked In', key: 'checkedIn', width: 12 },
    ];

    guestSheet.getRow(1).font = { bold: true };
    guestSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.guests.forEach((g) => {
      const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
      const additionalNames = g.additionalGuestNames || g.additional_guest_names || [];
      const arrivalDt = g.arrivalDatetime || g.arrival_datetime;
      const departureDt = g.departureDatetime || g.departure_datetime;
      const attendingEvents = g.attendingEvents || g.attending_events || [];

      guestSheet.addRow({
        id: g.id || '',
        name: name,
        email: g.email || '',
        phone: g.phone || '',
        group: g.groupName || g.group_name || g.group || '',
        side: g.guestSide || g.guest_side || '',
        rsvp: g.rsvpStatus || g.rsvp_status || 'pending',
        partySize: g.partySize || g.party_size || 1,
        additionalGuests: Array.isArray(additionalNames) ? additionalNames.join(', ') : '',
        relationship: g.relationshipToFamily || g.relationship_to_family || '',
        eventsAttending: Array.isArray(attendingEvents) ? attendingEvents.join(', ') : '',
        arrivalDatetime: arrivalDt || '',
        arrivalMode: g.arrivalMode || g.arrival_mode || '',
        departureDatetime: departureDt || '',
        departureMode: g.departureMode || g.departure_mode || '',
        mealPreference: g.mealPreference || g.meal_preference || '',
        dietary: g.dietaryRestrictions || g.dietary_restrictions || '',
        hotelRequired: (g.hotelRequired || g.hotel_required) ? 'TRUE' : 'FALSE',
        transportRequired: (g.transportRequired || g.transport_required) ? 'TRUE' : 'FALSE',
        giftRequired: (g.giftRequired || g.gift_required) ? 'TRUE' : 'FALSE',
        giftToGive: g.giftToGive || g.gift_to_give || '',
        notes: g.notes || '',
        checkedIn: (g.checkedIn || g.checked_in) ? 'Yes' : 'No',
      });
    });
  }

  // Hotels Sheet - Full round-trip compatible with import template
  if (data.hotels.length > 0) {
    const hotelSheet = workbook.addWorksheet('Hotels');
    hotelSheet.columns = [
      { header: 'ID (Do not modify)', key: 'id', width: 40 },
      { header: 'Guest ID (Do not modify)', key: 'guestId', width: 40 },
      { header: 'Guest Name * (Required)', key: 'guestName', width: 25 },
      { header: 'Relationship (from guest list)', key: 'guestRelationship', width: 28 },
      { header: 'Additional Guest Names (from guest list)', key: 'additionalGuestNames', width: 35 },
      { header: 'Guest Names in Room (e.g., john and mary, sue)', key: 'guestNamesInRoom', width: 40 },
      { header: '# in Room (auto or manual)', key: 'partySize', width: 22 },
      { header: 'Email Address', key: 'guestEmail', width: 28 },
      { header: 'Phone Number', key: 'guestPhone', width: 18 },
      { header: 'Need Hotel? (Yes/No)', key: 'accommodationNeeded', width: 18 },
      { header: 'Hotel Name', key: 'hotelName', width: 25 },
      { header: 'Room Number', key: 'roomNumber', width: 15 },
      { header: 'Room Type (Suite/Deluxe...)', key: 'roomType', width: 23 },
      { header: 'Check-In (YYYY-MM-DD)', key: 'checkInDate', width: 20 },
      { header: 'Check-Out (YYYY-MM-DD)', key: 'checkOutDate', width: 20 },
      { header: 'Booking Confirmed (Yes/No)', key: 'bookingConfirmed', width: 23 },
      { header: 'Checked In (Yes/No)', key: 'checkedIn', width: 18 },
      { header: 'Room Cost (numbers only)', key: 'cost', width: 22 },
      { header: 'Payment (pending/paid/overdue)', key: 'paymentStatus', width: 28 },
      { header: 'Special Notes', key: 'notes', width: 40 },
    ];

    hotelSheet.getRow(1).font = { bold: true };
    hotelSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    // Create guest lookup map for enriching hotel data
    const guestLookup = new Map(data.guests.map((g: any) => [g.id, g]));

    data.hotels.forEach((h) => {
      const guest = guestLookup.get(h.guestId || h.guest_id);
      const guestName = h.guestName || h.guest_name || (guest ? `${guest.firstName || guest.first_name || ''} ${guest.lastName || guest.last_name || ''}`.trim() : '');
      const additionalNames = guest?.additionalGuestNames || guest?.additional_guest_names || [];

      hotelSheet.addRow({
        id: h.id || '',
        guestId: h.guestId || h.guest_id || '',
        guestName: guestName,
        guestRelationship: h.guestRelationship || guest?.relationshipToFamily || guest?.relationship_to_family || '',
        additionalGuestNames: Array.isArray(additionalNames) ? additionalNames.join(', ') : (additionalNames || ''),
        guestNamesInRoom: '',
        partySize: h.partySize || h.party_size || 1,
        guestEmail: h.guestEmail || guest?.email || '',
        guestPhone: h.guestPhone || guest?.phone || '',
        accommodationNeeded: (h.accommodationNeeded || h.accommodation_needed) ? 'Yes' : 'No',
        hotelName: h.hotelName || h.hotel_name || '',
        roomNumber: h.roomNumber || h.room_number || '',
        roomType: h.roomType || h.room_type || '',
        checkInDate: h.checkInDate || h.check_in_date || '',
        checkOutDate: h.checkOutDate || h.check_out_date || '',
        bookingConfirmed: (h.bookingConfirmed || h.booking_confirmed) ? 'Yes' : 'No',
        checkedIn: (h.checkedIn || h.checked_in) ? 'Yes' : 'No',
        cost: h.cost || '',
        paymentStatus: h.paymentStatus || h.payment_status || 'pending',
        notes: h.notes || '',
      });
    });
  }

  // Gifts Sheet - Enhanced with delivery management fields
  if (data.gifts.length > 0) {
    const giftSheet = workbook.addWorksheet('Gifts');
    giftSheet.columns = [
      { header: 'Serial #', key: 'serial', width: 10 },
      // Guest Information
      { header: 'Guest Name', key: 'guestName', width: 25 },
      { header: 'Guest Group', key: 'guestGroup', width: 18 },
      // Gift Information
      { header: 'Gift Item', key: 'giftItem', width: 30 },
      { header: 'Gift Category', key: 'giftType', width: 20 },
      { header: 'Quantity', key: 'quantity', width: 12 },
      // Delivery Scheduling
      { header: 'Delivery Date', key: 'deliveryDate', width: 15 },
      { header: 'Delivery Time', key: 'deliveryTime', width: 15 },
      { header: 'Delivery Location', key: 'deliveryLocation', width: 30 },
      // Status & Tracking
      { header: 'Delivery Status', key: 'deliveryStatus', width: 18 },
      { header: 'Delivered By', key: 'deliveredBy', width: 20 },
      { header: 'Delivered On', key: 'deliveredAt', width: 18 },
      // Legacy fields for backwards compatibility
      { header: 'Guest Name', key: 'from', width: 25 },
      { header: 'Thank You Sent', key: 'thankYou', width: 18 },
      { header: 'Special Notes', key: 'notes', width: 40 },
    ];

    giftSheet.getRow(1).font = { bold: true };
    giftSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.gifts.forEach((g, idx) => {
      // Handle both snake_case and camelCase field names
      const guestName = g.guest_name || g.guestName ||
        (g.guest ? `${g.guest.firstName || g.guest.first_name || ''} ${g.guest.lastName || g.guest.last_name || ''}`.trim() : '');
      const guestGroup = g.guest_group || g.guestGroup || g.guest?.groupName || g.guest?.group_name || '';
      const giftItem = g.gift_item || g.giftItem || g.giftName || g.gift_name || '';
      const giftType = g.gift_type || g.giftType || g.giftTypeName || g.gift_type_name || '';
      const deliveryDate = g.delivery_date || g.deliveryDate;
      const deliveryTime = g.delivery_time || g.deliveryTime;
      const deliveryLocation = g.delivery_location || g.deliveryLocation;
      const deliveredAt = g.delivered_at || g.deliveredAt;

      giftSheet.addRow({
        serial: idx + 1,
        guestName: guestName,
        guestGroup: guestGroup,
        giftItem: giftItem,
        giftType: giftType,
        quantity: g.quantity || 1,
        deliveryDate: deliveryDate ? new Date(deliveryDate).toLocaleDateString() : '',
        deliveryTime: deliveryTime || '',
        deliveryLocation: deliveryLocation || '',
        deliveryStatus: g.delivery_status || g.deliveryStatus || 'pending',
        deliveredBy: g.delivered_by || g.deliveredBy || '',
        deliveredAt: deliveredAt ? new Date(deliveredAt).toLocaleString() : '',
        from: g.from_name || g.fromName || '',
        thankYou: (g.thank_you_sent || g.thankYouSent) ? 'Sent' : 'Pending',
        notes: g.notes || g.delivery_notes || g.deliveryNotes || '',
      });
    });
  }

  // Transport Sheet - Full round-trip compatible with import template
  if (data.transport && data.transport.length > 0) {
    const transportSheet = workbook.addWorksheet('Transport');
    transportSheet.columns = [
      { header: 'ID (Do not modify)', key: 'id', width: 40 },
      { header: 'Guest ID (Do not modify)', key: 'guestId', width: 40 },
      { header: 'Guest Name *', key: 'guestName', width: 25 },
      { header: 'Guest Email', key: 'guestEmail', width: 25 },
      { header: 'Guest Phone', key: 'guestPhone', width: 15 },
      { header: 'Guest Group', key: 'guestGroup', width: 15 },
      { header: 'Pickup Date', key: 'pickupDate', width: 15 },
      { header: 'Pickup Time', key: 'pickupTime', width: 12 },
      { header: 'Pickup From', key: 'pickupFrom', width: 28 },
      { header: 'Drop To', key: 'dropTo', width: 28 },
      { header: 'Vehicle Info', key: 'vehicleInfo', width: 25 },
      { header: 'Transport Status', key: 'transportStatus', width: 15 },
      { header: 'Notes', key: 'notes', width: 40 },
    ];

    transportSheet.getRow(1).font = { bold: true };
    transportSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.transport.forEach((t) => {
      const guest = t.guest;
      transportSheet.addRow({
        id: t.id || '',
        guestId: t.guestId || t.guest_id || '',
        guestName: t.guestName || t.guest_name || '',
        guestEmail: t.guestEmail || t.guest_email || guest?.email || '',
        guestPhone: t.guestPhone || t.guest_phone || guest?.phone || '',
        guestGroup: t.guestGroup || t.guest_group || guest?.groupName || guest?.group_name || '',
        pickupDate: t.pickupDate || t.pickup_date || '',
        pickupTime: t.pickupTime || t.pickup_time || '',
        pickupFrom: t.pickupFrom || t.pickup_from || '',
        dropTo: t.dropTo || t.drop_to || '',
        vehicleInfo: t.vehicleInfo || t.vehicle_info || '',
        transportStatus: t.transportStatus || t.transport_status || 'scheduled',
        notes: t.notes || '',
      });
    });
  }

  // Vendors Sheet - Full round-trip compatible with import template
  if (data.vendors.length > 0) {
    const vendorSheet = workbook.addWorksheet('Vendors');
    vendorSheet.columns = [
      { header: 'ID (Do not modify)', key: 'id', width: 40 },
      { header: 'Vendor Name *', key: 'vendorName', width: 30 },
      { header: 'Category *', key: 'category', width: 20 },
      { header: 'Contact Name', key: 'contactName', width: 25 },
      { header: 'Phone', key: 'phone', width: 18 },
      { header: 'Email', key: 'email', width: 28 },
      { header: 'Contract Amount', key: 'contractAmount', width: 18 },
      { header: 'Payment Status', key: 'paymentStatus', width: 18 },
      { header: 'Rating', key: 'rating', width: 10 },
      { header: 'Notes', key: 'notes', width: 30 },
    ];

    vendorSheet.getRow(1).font = { bold: true };
    vendorSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.vendors.forEach((v) => {
      vendorSheet.addRow({
        id: v.id || '',
        vendorName: v.name || v.vendor_name || '',
        category: v.category || '',
        contactName: v.contactName || v.contact_name || '',
        phone: v.phone || '',
        email: v.email || '',
        contractAmount: v.contractAmount || v.cost || '',
        paymentStatus: v.paymentStatus || v.payment_status || 'pending',
        rating: v.rating || '',
        notes: v.notes || '',
      });
    });
  }

  // Budget Sheet - Full round-trip compatible with import template
  if (data.budget.length > 0) {
    const budgetSheet = workbook.addWorksheet('Budget');
    budgetSheet.columns = [
      { header: 'ID (Do not modify)', key: 'id', width: 40 },
      { header: 'Item *', key: 'item', width: 25 },
      { header: 'Category *', key: 'category', width: 20 },
      { header: 'Segment', key: 'segment', width: 15 },
      { header: 'Estimated Cost *', key: 'estimatedCost', width: 18 },
      { header: 'Paid Amount', key: 'paidAmount', width: 18 },
      { header: 'Actual Cost', key: 'actualCost', width: 18 },
      { header: 'Payment Status', key: 'paymentStatus', width: 18 },
      { header: 'Notes', key: 'notes', width: 30 },
    ];

    budgetSheet.getRow(1).font = { bold: true };
    budgetSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.budget.forEach((b) => {
      budgetSheet.addRow({
        id: b.id || '',
        item: b.item || '',
        category: b.category || '',
        segment: b.segment || 'other',
        estimatedCost: b.estimatedCost || b.estimated_cost || 0,
        paidAmount: b.paidAmount || b.paid_amount || 0,
        actualCost: b.actualCost || b.actual_cost || '',
        paymentStatus: b.paymentStatus || b.payment_status || 'pending',
        notes: b.notes || '',
      });
    });
  }

  // Timeline Sheet
  if (data.timeline.length > 0) {
    const timelineSheet = workbook.addWorksheet('Timeline');
    timelineSheet.columns = [
      { header: 'Activity', key: 'event', width: 35 },
      { header: 'Start Time', key: 'startTime', width: 15 },
      { header: 'Duration', key: 'duration', width: 15 },
      { header: 'Location', key: 'location', width: 30 },
      { header: 'Special Notes', key: 'notes', width: 40 },
    ];

    timelineSheet.getRow(1).font = { bold: true };
    timelineSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' },
    };

    data.timeline.forEach((t) => {
      timelineSheet.addRow({
        event: t.title,
        startTime: t.start_time,
        duration: `${t.duration_minutes} min`,
        location: t.location || '',
        notes: t.notes || '',
      });
    });
  }

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return buffer as ArrayBuffer;
}

export async function exportToPDF(data: ExportData): Promise<ArrayBuffer> {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text(data.company.name, 15, 20);

  doc.setFontSize(16);
  doc.text(`Wedding: ${data.client.name}`, 15, 35);

  doc.setFontSize(12);
  doc.text(`Date: ${new Date(data.client.wedding_date).toLocaleDateString()}`, 15, 45);

  let yPosition = 60;

  // Guest List Table - Comprehensive view with all 15 fields
  if (data.guests.length > 0) {
    doc.setFontSize(14);
    doc.text('Guest List', 15, yPosition);
    yPosition += 10;

    // Main Guest Info Table
    autoTable(doc, {
      head: [['#', 'Name', 'Phone', 'Email', 'Party', 'Relationship', 'RSVP']],
      body: data.guests.map((g, idx) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        return [
          idx + 1,
          name,
          g.phone || '-',
          g.email || '-',
          g.partySize || g.party_size || 1,
          g.relationshipToFamily || g.relationship_to_family || '-',
          g.rsvpStatus || g.rsvp_status || 'pending',
        ];
      }),
      startY: yPosition,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [100, 100, 100] },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;

    // Travel & Accommodation Summary
    if (yPosition > 200) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.text('Travel & Accommodation Details', 15, yPosition);
    yPosition += 8;

    const travelData = data.guests
      .filter((g: any) => (g.arrivalDatetime || g.arrival_datetime) || (g.hotelRequired || g.hotel_required) || (g.transportRequired || g.transport_required))
      .map((g: any) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        const arrivalDt = g.arrivalDatetime || g.arrival_datetime;
        const departureDt = g.departureDatetime || g.departure_datetime;
        return [
          name,
          arrivalDt ? new Date(arrivalDt).toLocaleDateString() : '-',
          g.arrivalMode || g.arrival_mode || '-',
          departureDt ? new Date(departureDt).toLocaleDateString() : '-',
          (g.hotelRequired || g.hotel_required) ? '✓' : '○',
          (g.transportRequired || g.transport_required) ? '✓' : '○',
        ];
      });

    if (travelData.length > 0) {
      autoTable(doc, {
        head: [['Guest', 'Arrival', 'Mode', 'Departure', 'Hotel', 'Transport']],
        body: travelData,
        startY: yPosition,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [80, 80, 80] },
      });
      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.text('No travel details recorded', 15, yPosition);
      yPosition += 10;
    }

    // Special Requirements & Gifts Summary
    if (yPosition > 230) {
      doc.addPage();
      yPosition = 20;
    }

    const specialReqs = data.guests
      .filter((g: any) => g.notes || g.giftToGive || g.gift_to_give || g.dietaryRestrictions || g.dietary_restrictions)
      .map((g: any) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        return [
          name,
          g.dietaryRestrictions || g.dietary_restrictions || '-',
          g.giftToGive || g.gift_to_give || '-',
          (g.notes || '').substring(0, 50) + (g.notes && g.notes.length > 50 ? '...' : ''),
        ];
      });

    if (specialReqs.length > 0) {
      doc.setFontSize(12);
      doc.text('Special Requirements & Gifts', 15, yPosition);
      yPosition += 8;

      autoTable(doc, {
        head: [['Guest', 'Dietary', 'Gift to Give', 'Notes']],
        body: specialReqs,
        startY: yPosition,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [80, 80, 80] },
      });
      yPosition = (doc as any).lastAutoTable.finalY + 15;
    }
  }

  // Budget Summary
  if (data.budget.length > 0) {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.text('Budget Summary', 15, yPosition);
    yPosition += 10;

    autoTable(doc, {
      head: [['Category', 'Estimated', 'Actual', 'Status']],
      body: data.budget.map((b) => [
        b.category,
        `${b.estimated_cost}`,
        b.actual_cost ? `${b.actual_cost}` : '-',
        b.payment_status || 'pending',
      ]),
      startY: yPosition,
      styles: { fontSize: 9 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 15;
  }

  // Vendors
  if (data.vendors.length > 0) {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.text('Vendors', 15, yPosition);
    yPosition += 10;

    autoTable(doc, {
      head: [['Vendor', 'Category', 'Contact', 'Cost']],
      body: data.vendors.map((v) => [
        v.vendor_name,
        v.category,
        v.contact_name || '',
        v.cost ? `${v.cost}` : '-',
      ]),
      startY: yPosition,
      styles: { fontSize: 9 },
    });
  }

  // Footer on all pages
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by WeddingFlo`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('arraybuffer');
}
