/**
 * Export utilities - Excel and PDF
 * Uses ExcelJS for Excel exports (secure replacement for xlsx)
 */

import ExcelJS from 'exceljs';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { buildExportSheet } from '@/lib/import/module-shape';

interface ExportData {
  company: {
    name: string;
    logo_url?: string;
  };
  client: {
    name: string;
    wedding_date: string;
  };
  guests: any[];
  hotels: any[];
  gifts: any[];
  transport?: any[];
  vendors: any[];
  budget: any[];
  events: any[];
  timeline: any[];
  documents: any[];
}

export async function exportToExcel(data: ExportData): Promise<ArrayBuffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'WeddingFlo';
  workbook.created = new Date();

  // Cover sheet
  const coverSheet = workbook.addWorksheet('Cover');
  coverSheet.addRow([data.company.name]);
  coverSheet.addRow([]);
  coverSheet.addRow([`Wedding: ${data.client.name}`]);
  coverSheet.addRow([`Date: ${new Date(data.client.wedding_date).toLocaleDateString()}`]);
  coverSheet.addRow([]);
  coverSheet.addRow(['Generated by WeddingFlo']);
  coverSheet.addRow([`Export Date: ${new Date().toLocaleString()}`]);

  // Style cover sheet
  coverSheet.getRow(1).font = { bold: true, size: 16 };
  coverSheet.getRow(3).font = { bold: true, size: 14 };

  // ── Module data sheets — built from the single-source column SHAPE (Cluster E) ──
  // Each module's header label / order / required marker / formatter lives in
  // `MODULE_SHAPES` (src/lib/import/module-shape.ts), consumed here AND by the import
  // service (import-cascade.ts) so the export→import round-trip contract can't drift.
  if (data.guests.length > 0) {
    buildExportSheet(workbook, 'guests', data.guests);
  }

  if (data.hotels.length > 0) {
    // Pre-enrich each hotel row with its guest record so the shape formatters can derive
    // guest name / relationship / contact when the hotel row itself doesn't carry them.
    const guestLookup = new Map(data.guests.map((g: any) => [g.id, g]));
    const enrichedHotels = data.hotels.map((h: any) => ({
      ...h,
      __guest: guestLookup.get(h.guestId || h.guest_id),
    }));
    buildExportSheet(workbook, 'hotels', enrichedHotels);
  }

  // [E3] Gift sheet = the gift-DELIVERY model (`guest_gifts`) per handbook §G.7, emitted as
  // a round-trippable 'GiftsGiven' sheet (leading ID + required Gift Name) instead of the old
  // view-only 'Serial #' sheet. `data.gifts` carries the delivery rows (see export.router).
  if (data.gifts.length > 0) {
    buildExportSheet(workbook, 'guestGifts', data.gifts);
  }

  if (data.transport && data.transport.length > 0) {
    buildExportSheet(workbook, 'transport', data.transport);
  }

  if (data.vendors.length > 0) {
    buildExportSheet(workbook, 'vendors', data.vendors);
  }

  if (data.budget.length > 0) {
    buildExportSheet(workbook, 'budget', data.budget);
  }

  // [E1] Events are now part of the combined export (was absent → no combined round-trip).
  if (data.events && data.events.length > 0) {
    buildExportSheet(workbook, 'events', data.events);
  }

  // Timeline stays view-only in the combined export (handbook §G.8); the round-trip path is
  // the dedicated exportTimelineExcel → timeline.bulkImport.
  if (data.timeline.length > 0) {
    buildExportSheet(workbook, 'timeline', data.timeline);
  }

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return buffer as ArrayBuffer;
}

export async function exportToPDF(data: ExportData): Promise<ArrayBuffer> {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text(data.company.name, 15, 20);

  doc.setFontSize(16);
  doc.text(`Wedding: ${data.client.name}`, 15, 35);

  doc.setFontSize(12);
  doc.text(`Date: ${new Date(data.client.wedding_date).toLocaleDateString()}`, 15, 45);

  let yPosition = 60;

  // Guest List Table - Comprehensive view with all 15 fields
  if (data.guests.length > 0) {
    doc.setFontSize(14);
    doc.text('Guest List', 15, yPosition);
    yPosition += 10;

    // Main Guest Info Table
    autoTable(doc, {
      head: [['#', 'Name', 'Phone', 'Email', 'Party', 'Relationship', 'RSVP']],
      body: data.guests.map((g, idx) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        return [
          idx + 1,
          name,
          g.phone || '-',
          g.email || '-',
          g.partySize || g.party_size || 1,
          g.relationshipToFamily || g.relationship_to_family || '-',
          g.rsvpStatus || g.rsvp_status || 'pending',
        ];
      }),
      startY: yPosition,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [100, 100, 100] },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;

    // Travel & Accommodation Summary
    if (yPosition > 200) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.text('Travel & Accommodation Details', 15, yPosition);
    yPosition += 8;

    const travelData = data.guests
      .filter((g: any) => (g.arrivalDatetime || g.arrival_datetime) || (g.hotelRequired || g.hotel_required) || (g.transportRequired || g.transport_required))
      .map((g: any) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        const arrivalDt = g.arrivalDatetime || g.arrival_datetime;
        const departureDt = g.departureDatetime || g.departure_datetime;
        return [
          name,
          arrivalDt ? new Date(arrivalDt).toLocaleDateString() : '-',
          g.arrivalMode || g.arrival_mode || '-',
          departureDt ? new Date(departureDt).toLocaleDateString() : '-',
          (g.hotelRequired || g.hotel_required) ? '✓' : '○',
          (g.transportRequired || g.transport_required) ? '✓' : '○',
        ];
      });

    if (travelData.length > 0) {
      autoTable(doc, {
        head: [['Guest', 'Arrival', 'Mode', 'Departure', 'Hotel', 'Transport']],
        body: travelData,
        startY: yPosition,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [80, 80, 80] },
      });
      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.text('No travel details recorded', 15, yPosition);
      yPosition += 10;
    }

    // Special Requirements & Gifts Summary
    if (yPosition > 230) {
      doc.addPage();
      yPosition = 20;
    }

    const specialReqs = data.guests
      .filter((g: any) => g.notes || g.giftToGive || g.gift_to_give || g.dietaryRestrictions || g.dietary_restrictions)
      .map((g: any) => {
        const name = g.name || `${g.firstName || g.first_name || ''} ${g.lastName || g.last_name || ''}`.trim();
        return [
          name,
          g.dietaryRestrictions || g.dietary_restrictions || '-',
          g.giftToGive || g.gift_to_give || '-',
          (g.notes || '').substring(0, 50) + (g.notes && g.notes.length > 50 ? '...' : ''),
        ];
      });

    if (specialReqs.length > 0) {
      doc.setFontSize(12);
      doc.text('Special Requirements & Gifts', 15, yPosition);
      yPosition += 8;

      autoTable(doc, {
        head: [['Guest', 'Dietary', 'Gift to Give', 'Notes']],
        body: specialReqs,
        startY: yPosition,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [80, 80, 80] },
      });
      yPosition = (doc as any).lastAutoTable.finalY + 15;
    }
  }

  // Budget Summary
  if (data.budget.length > 0) {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.text('Budget Summary', 15, yPosition);
    yPosition += 10;

    autoTable(doc, {
      head: [['Category', 'Estimated', 'Actual', 'Status']],
      body: data.budget.map((b) => [
        b.category,
        `${b.estimated_cost}`,
        b.actual_cost ? `${b.actual_cost}` : '-',
        b.payment_status || 'pending',
      ]),
      startY: yPosition,
      styles: { fontSize: 9 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 15;
  }

  // Vendors
  if (data.vendors.length > 0) {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.text('Vendors', 15, yPosition);
    yPosition += 10;

    autoTable(doc, {
      head: [['Vendor', 'Category', 'Contact', 'Cost']],
      body: data.vendors.map((v) => [
        v.vendor_name,
        v.category,
        v.contact_name || '',
        v.cost ? `${v.cost}` : '-',
      ]),
      startY: yPosition,
      styles: { fontSize: 9 },
    });
  }

  // Footer on all pages
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by WeddingFlo`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('arraybuffer');
}
