-- Schema Reconciliation Migration (idempotent)
-- Generated by Drizzle, rewritten to be safe for re-running.
-- This migration reconciles the Drizzle-managed schema with manually-applied migrations.
-- All statements are idempotent: CREATE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS,
-- DROP CONSTRAINT IF EXISTS, and DO blocks with EXCEPTION handlers.

-- SECTION 1: Drop old FK constraints
-- Drop old-named FK constraints so they can be re-created with Drizzle naming conventions.

ALTER TABLE "accommodations" DROP CONSTRAINT IF EXISTS "accommodations_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "activity" DROP CONSTRAINT IF EXISTS "activity_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "advance_payments" DROP CONSTRAINT IF EXISTS "advance_payments_budget_item_id_fkey";
--> statement-breakpoint
ALTER TABLE "advance_payments" DROP CONSTRAINT IF EXISTS "advance_payments_vendor_id_fkey";
--> statement-breakpoint
ALTER TABLE "budget" DROP CONSTRAINT IF EXISTS "budget_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "budget" DROP CONSTRAINT IF EXISTS "budget_vendor_id_fkey";
--> statement-breakpoint
ALTER TABLE "budget" DROP CONSTRAINT IF EXISTS "budget_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "calendar_synced_events" DROP CONSTRAINT IF EXISTS "calendar_synced_events_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "client_users" DROP CONSTRAINT IF EXISTS "client_users_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "client_vendors" DROP CONSTRAINT IF EXISTS "client_vendors_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "client_vendors" DROP CONSTRAINT IF EXISTS "client_vendors_vendor_id_fkey";
--> statement-breakpoint
ALTER TABLE "client_vendors" DROP CONSTRAINT IF EXISTS "client_vendors_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "creative_jobs" DROP CONSTRAINT IF EXISTS "creative_jobs_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "documents" DROP CONSTRAINT IF EXISTS "documents_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "email_logs" DROP CONSTRAINT IF EXISTS "email_logs_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT IF EXISTS "events_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" DROP CONSTRAINT IF EXISTS "floor_plan_guests_floor_plan_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" DROP CONSTRAINT IF EXISTS "floor_plan_guests_table_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" DROP CONSTRAINT IF EXISTS "floor_plan_guests_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" DROP CONSTRAINT IF EXISTS "floor_plan_tables_floor_plan_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plans" DROP CONSTRAINT IF EXISTS "floor_plans_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "floor_plans" DROP CONSTRAINT IF EXISTS "floor_plans_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "generated_reports" DROP CONSTRAINT IF EXISTS "generated_reports_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "gifts" DROP CONSTRAINT IF EXISTS "gifts_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "gifts" DROP CONSTRAINT IF EXISTS "gifts_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "gifts_enhanced" DROP CONSTRAINT IF EXISTS "gifts_enhanced_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_conflicts" DROP CONSTRAINT IF EXISTS "guest_conflicts_guest1_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_conflicts" DROP CONSTRAINT IF EXISTS "guest_conflicts_guest2_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_gifts" DROP CONSTRAINT IF EXISTS "guest_gifts_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_gifts" DROP CONSTRAINT IF EXISTS "guest_gifts_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_preferences" DROP CONSTRAINT IF EXISTS "guest_preferences_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_transport" DROP CONSTRAINT IF EXISTS "guest_transport_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_transport" DROP CONSTRAINT IF EXISTS "guest_transport_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "guest_transport" DROP CONSTRAINT IF EXISTS "guest_transport_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "guests" DROP CONSTRAINT IF EXISTS "guests_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "hotel_bookings" DROP CONSTRAINT IF EXISTS "hotel_bookings_hotel_id_fkey";
--> statement-breakpoint
ALTER TABLE "hotel_bookings" DROP CONSTRAINT IF EXISTS "hotel_bookings_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "hotels" DROP CONSTRAINT IF EXISTS "hotels_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "hotels" DROP CONSTRAINT IF EXISTS "hotels_guest_id_fkey";
--> statement-breakpoint
ALTER TABLE "invoices" DROP CONSTRAINT IF EXISTS "invoices_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "messages" DROP CONSTRAINT IF EXISTS "messages_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "qr_codes" DROP CONSTRAINT IF EXISTS "qr_codes_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "seating_change_log" DROP CONSTRAINT IF EXISTS "seating_change_log_floor_plan_id_fkey";
--> statement-breakpoint
ALTER TABLE "seating_versions" DROP CONSTRAINT IF EXISTS "seating_versions_floor_plan_id_fkey";
--> statement-breakpoint
ALTER TABLE "sms_logs" DROP CONSTRAINT IF EXISTS "sms_logs_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "team_client_assignments" DROP CONSTRAINT IF EXISTS "team_client_assignments_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "timeline" DROP CONSTRAINT IF EXISTS "timeline_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "timeline" DROP CONSTRAINT IF EXISTS "timeline_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "vendor_comments" DROP CONSTRAINT IF EXISTS "vendor_comments_vendor_id_fkey";
--> statement-breakpoint
ALTER TABLE "website_builder_content" DROP CONSTRAINT IF EXISTS "website_builder_content_page_id_fkey";
--> statement-breakpoint
ALTER TABLE "website_builder_pages" DROP CONSTRAINT IF EXISTS "website_builder_pages_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "wedding_websites" DROP CONSTRAINT IF EXISTS "wedding_websites_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "whatsapp_logs" DROP CONSTRAINT IF EXISTS "whatsapp_logs_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "vendor_reviews" DROP CONSTRAINT IF EXISTS "vendor_reviews_vendor_id_fkey";
--> statement-breakpoint
ALTER TABLE "vendor_reviews" DROP CONSTRAINT IF EXISTS "vendor_reviews_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "chatbot_command_templates" DROP CONSTRAINT IF EXISTS "chatbot_command_templates_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "chatbot_conversations" DROP CONSTRAINT IF EXISTS "chatbot_conversations_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "chatbot_conversations" DROP CONSTRAINT IF EXISTS "chatbot_conversations_client_id_fkey";
--> statement-breakpoint
ALTER TABLE "chatbot_messages" DROP CONSTRAINT IF EXISTS "chatbot_messages_conversation_id_fkey";
--> statement-breakpoint

-- SECTION 2: Create tables (IF NOT EXISTS)
-- rate_limit_entries and chatbot_pending_calls are OMITTED (UNLOGGED tables from migration 0017).

CREATE TABLE IF NOT EXISTS "webhook_events" (
	"id" text PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"processed" boolean DEFAULT false,
	"processed_at" timestamp,
	"payload" text,
	"error" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "google_sheets_sync_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"company_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"token_expires_at" timestamp,
	"is_connected" boolean DEFAULT false,
	"spreadsheet_id" text,
	"spreadsheet_url" text,
	"last_synced_at" timestamp,
	"sync_direction" text DEFAULT 'bidirectional',
	"auto_sync" boolean DEFAULT false,
	"auto_sync_interval" integer DEFAULT 60,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vendor_reviews" (
	"id" text PRIMARY KEY NOT NULL,
	"vendor_id" text NOT NULL,
	"client_id" text NOT NULL,
	"user_id" text NOT NULL,
	"rating" integer NOT NULL,
	"review_text" text,
	"service_quality" integer,
	"communication" integer,
	"value_for_money" integer,
	"would_recommend" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "team_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text DEFAULT 'staff' NOT NULL,
	"token" text NOT NULL,
	"invited_by" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"accepted_at" timestamp,
	"accepted_by" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "team_invitations_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "wedding_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" text NOT NULL,
	"company_id" text NOT NULL,
	"email" text NOT NULL,
	"relationship" text,
	"token" text NOT NULL,
	"invited_by" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"accepted_at" timestamp,
	"accepted_by" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "wedding_invitations_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chatbot_command_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"company_id" text NOT NULL,
	"name" text NOT NULL,
	"command" text NOT NULL,
	"description" text,
	"icon" text,
	"category" text DEFAULT 'custom',
	"usage_count" integer DEFAULT 0,
	"last_used_at" timestamp with time zone,
	"is_pinned" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chatbot_conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"client_id" text,
	"company_id" text NOT NULL,
	"title" text,
	"summary" text,
	"message_count" integer DEFAULT 0,
	"last_message_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chatbot_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"company_id" text,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"tool_name" text,
	"tool_args" jsonb,
	"tool_result" jsonb,
	"status" text DEFAULT 'success',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- SECTION 3: Add columns (IF NOT EXISTS)
-- Columns already added by migration 0023 are OMITTED:
--   activity.company_id, budget.company_id, events.company_id, floor_plans.company_id,
--   gifts.company_id, guest_transport.company_id, guests.company_id, hotels.company_id,
--   timeline.company_id

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "avatar_url" text;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true;
--> statement-breakpoint
ALTER TABLE "activity" ADD COLUMN IF NOT EXISTS "action" text;
--> statement-breakpoint
ALTER TABLE "activity" ADD COLUMN IF NOT EXISTS "ip_address" text;
--> statement-breakpoint
ALTER TABLE "activity" ADD COLUMN IF NOT EXISTS "user_agent" text;
--> statement-breakpoint
ALTER TABLE "budget" ADD COLUMN IF NOT EXISTS "per_guest_cost" text;
--> statement-breakpoint
ALTER TABLE "budget" ADD COLUMN IF NOT EXISTS "is_per_guest_item" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "client_users" ADD COLUMN IF NOT EXISTS "company_id" text;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD COLUMN IF NOT EXISTS "floor_plan_id" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD COLUMN IF NOT EXISTS "x" integer;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD COLUMN IF NOT EXISTS "y" integer;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "table_number" integer DEFAULT 1 NOT NULL;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "table_name" text;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "width" integer DEFAULT 100;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "height" integer DEFAULT 100;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "rotation" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD COLUMN IF NOT EXISTS "width" integer DEFAULT 1200;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD COLUMN IF NOT EXISTS "height" integer DEFAULT 800;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD COLUMN IF NOT EXISTS "background_image" text;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "company_id" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "subject" text;
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "message_type" text DEFAULT 'direct';
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "parent_id" text;
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp;
--> statement-breakpoint
ALTER TABLE "sms_preferences" ADD COLUMN IF NOT EXISTS "sms_enabled" boolean DEFAULT true;
--> statement-breakpoint
ALTER TABLE "sms_preferences" ADD COLUMN IF NOT EXISTS "marketing_sms" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "sms_preferences" ADD COLUMN IF NOT EXISTS "transactional_sms" boolean DEFAULT true;
--> statement-breakpoint
ALTER TABLE "sms_preferences" ADD COLUMN IF NOT EXISTS "reminder_sms" boolean DEFAULT true;
--> statement-breakpoint
ALTER TABLE "sms_preferences" ADD COLUMN IF NOT EXISTS "phone_number" text;
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "company_id" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "country" text DEFAULT 'US';
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "default_currency" text DEFAULT 'usd';
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "charges_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "payouts_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "details_submitted" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "stripe_accounts" ADD COLUMN IF NOT EXISTS "business_profile" jsonb;
--> statement-breakpoint
ALTER TABLE "stripe_connect_accounts" ADD COLUMN IF NOT EXISTS "type" text DEFAULT 'standard';
--> statement-breakpoint
ALTER TABLE "stripe_connect_accounts" ADD COLUMN IF NOT EXISTS "charges_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "stripe_connect_accounts" ADD COLUMN IF NOT EXISTS "payouts_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "stripe_connect_accounts" ADD COLUMN IF NOT EXISTS "details_submitted" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "vendors" ADD COLUMN IF NOT EXISTS "review_count" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "wedding_websites" ADD COLUMN IF NOT EXISTS "content" jsonb;
--> statement-breakpoint
ALTER TABLE "wedding_websites" ADD COLUMN IF NOT EXISTS "password" text;
--> statement-breakpoint
ALTER TABLE "wedding_websites" ADD COLUMN IF NOT EXISTS "is_password_protected" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "wedding_websites" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp;
--> statement-breakpoint

-- SECTION 4: Alter column types (idempotent DO blocks)

DO $$ BEGIN
ALTER TABLE "accommodations" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "budget" ALTER COLUMN "event_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "client_vendors" ALTER COLUMN "event_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "floor_plan_guests" ALTER COLUMN "guest_id" DROP NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "floor_plan_tables" ALTER COLUMN "x" SET DATA TYPE integer;
ALTER TABLE "floor_plan_tables" ALTER COLUMN "x" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "floor_plan_tables" ALTER COLUMN "y" SET DATA TYPE integer;
ALTER TABLE "floor_plan_tables" ALTER COLUMN "y" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "gift_categories" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "gift_types" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "guest_transport" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "guest_transport" ALTER COLUMN "guest_id" SET DATA TYPE text;
ALTER TABLE "guest_transport" ALTER COLUMN "guest_id" DROP NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "guest_transport" ALTER COLUMN "event_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "guests" ALTER COLUMN "id" SET DATA TYPE text;
ALTER TABLE "guests" ALTER COLUMN "id" DROP DEFAULT;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "guests" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "hotel_bookings" ALTER COLUMN "hotel_id" SET DATA TYPE uuid;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "hotels" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "hotels" ALTER COLUMN "guest_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "messages" ALTER COLUMN "client_id" DROP NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "messages" ALTER COLUMN "sender_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "messages" ALTER COLUMN "content" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "sms_templates" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "thank_you_note_templates" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "vehicles" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "vendors" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "whatsapp_templates" ALTER COLUMN "company_id" SET NOT NULL;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "questionnaires" ALTER COLUMN "client_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
ALTER TABLE "questionnaires" ALTER COLUMN "event_id" SET DATA TYPE text;
EXCEPTION WHEN others THEN NULL;
END $$;
--> statement-breakpoint

-- SECTION 5: Add Drizzle-named FK constraints

ALTER TABLE "vendor_reviews" ADD CONSTRAINT "vendor_reviews_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "vendor_reviews" ADD CONSTRAINT "vendor_reviews_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chatbot_command_templates" ADD CONSTRAINT "chatbot_command_templates_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "chatbot_conversations_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "chatbot_conversations_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "chatbot_messages" ADD CONSTRAINT "chatbot_messages_conversation_id_chatbot_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."chatbot_conversations"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "accommodations" ADD CONSTRAINT "accommodations_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "advance_payments" ADD CONSTRAINT "advance_payments_budget_item_id_budget_id_fk" FOREIGN KEY ("budget_item_id") REFERENCES "public"."budget"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "advance_payments" ADD CONSTRAINT "advance_payments_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "budget" ADD CONSTRAINT "budget_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "budget" ADD CONSTRAINT "budget_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "budget" ADD CONSTRAINT "budget_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "calendar_synced_events" ADD CONSTRAINT "calendar_synced_events_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "client_users" ADD CONSTRAINT "client_users_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "client_vendors" ADD CONSTRAINT "client_vendors_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "client_vendors" ADD CONSTRAINT "client_vendors_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "client_vendors" ADD CONSTRAINT "client_vendors_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "creative_jobs" ADD CONSTRAINT "creative_jobs_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "email_logs" ADD CONSTRAINT "email_logs_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD CONSTRAINT "floor_plan_guests_floor_plan_id_floor_plans_id_fk" FOREIGN KEY ("floor_plan_id") REFERENCES "public"."floor_plans"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD CONSTRAINT "floor_plan_guests_table_id_floor_plan_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."floor_plan_tables"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plan_guests" ADD CONSTRAINT "floor_plan_guests_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plan_tables" ADD CONSTRAINT "floor_plan_tables_floor_plan_id_floor_plans_id_fk" FOREIGN KEY ("floor_plan_id") REFERENCES "public"."floor_plans"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD CONSTRAINT "floor_plans_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "floor_plans" ADD CONSTRAINT "floor_plans_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "generated_reports" ADD CONSTRAINT "generated_reports_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "gifts" ADD CONSTRAINT "gifts_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "gifts" ADD CONSTRAINT "gifts_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "gifts_enhanced" ADD CONSTRAINT "gifts_enhanced_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_conflicts" ADD CONSTRAINT "guest_conflicts_guest1_id_guests_id_fk" FOREIGN KEY ("guest1_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_conflicts" ADD CONSTRAINT "guest_conflicts_guest2_id_guests_id_fk" FOREIGN KEY ("guest2_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_gifts" ADD CONSTRAINT "guest_gifts_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_gifts" ADD CONSTRAINT "guest_gifts_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_preferences" ADD CONSTRAINT "guest_preferences_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_transport" ADD CONSTRAINT "guest_transport_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_transport" ADD CONSTRAINT "guest_transport_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guest_transport" ADD CONSTRAINT "guest_transport_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "guests" ADD CONSTRAINT "guests_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
-- NOTE: hotel_bookings.hotel_id (TEXT) vs hotels.id (UUID) type mismatch - FK skipped
--> statement-breakpoint
ALTER TABLE "hotel_bookings" ADD CONSTRAINT "hotel_bookings_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "hotels" ADD CONSTRAINT "hotels_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "hotels" ADD CONSTRAINT "hotels_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "qr_codes" ADD CONSTRAINT "qr_codes_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "seating_change_log" ADD CONSTRAINT "seating_change_log_floor_plan_id_floor_plans_id_fk" FOREIGN KEY ("floor_plan_id") REFERENCES "public"."floor_plans"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "seating_versions" ADD CONSTRAINT "seating_versions_floor_plan_id_floor_plans_id_fk" FOREIGN KEY ("floor_plan_id") REFERENCES "public"."floor_plans"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "sms_logs" ADD CONSTRAINT "sms_logs_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "team_client_assignments" ADD CONSTRAINT "team_client_assignments_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "timeline" ADD CONSTRAINT "timeline_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "timeline" ADD CONSTRAINT "timeline_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "vendor_comments" ADD CONSTRAINT "vendor_comments_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "website_builder_content" ADD CONSTRAINT "website_builder_content_page_id_website_builder_pages_id_fk" FOREIGN KEY ("page_id") REFERENCES "public"."website_builder_pages"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "website_builder_pages" ADD CONSTRAINT "website_builder_pages_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "wedding_websites" ADD CONSTRAINT "wedding_websites_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "whatsapp_logs" ADD CONSTRAINT "whatsapp_logs_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint

-- SECTION 6: Create indexes (IF NOT EXISTS)
-- Indexes for rate_limit_entries and chatbot_pending_calls are OMITTED (UNLOGGED tables from migration 0017).

CREATE INDEX IF NOT EXISTS "webhook_events_event_id_idx" ON "webhook_events" USING btree ("event_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_events_provider_idx" ON "webhook_events" USING btree ("provider");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "google_sheets_sync_user_id_idx" ON "google_sheets_sync_settings" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "google_sheets_sync_company_id_idx" ON "google_sheets_sync_settings" USING btree ("company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vendor_reviews_vendor_id_idx" ON "vendor_reviews" USING btree ("vendor_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vendor_reviews_client_id_idx" ON "vendor_reviews" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_invitations_token_idx" ON "team_invitations" USING btree ("token");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_invitations_email_idx" ON "team_invitations" USING btree ("email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_invitations_company_id_idx" ON "team_invitations" USING btree ("company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wedding_invitations_token_idx" ON "wedding_invitations" USING btree ("token");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wedding_invitations_email_idx" ON "wedding_invitations" USING btree ("email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wedding_invitations_client_id_idx" ON "wedding_invitations" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_templates_user" ON "chatbot_command_templates" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_templates_user_company" ON "chatbot_command_templates" USING btree ("user_id","company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_templates_pinned" ON "chatbot_command_templates" USING btree ("user_id","is_pinned","usage_count");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_conv_user" ON "chatbot_conversations" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_conv_user_company" ON "chatbot_conversations" USING btree ("user_id","company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_conv_updated" ON "chatbot_conversations" USING btree ("user_id","updated_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_msg_conv" ON "chatbot_messages" USING btree ("conversation_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chatbot_msg_created" ON "chatbot_messages" USING btree ("conversation_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "account" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_company_id_idx" ON "user" USING btree ("company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_email_idx" ON "user" USING btree ("email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" USING btree ("identifier");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_client_id_idx" ON "activity" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_user_id_idx" ON "activity" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_company_id_idx" ON "activity" USING btree ("company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_type_action_idx" ON "activity" USING btree ("type","action");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "advance_payments_budget_item_id_idx" ON "advance_payments" USING btree ("budget_item_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "budget_client_id_idx" ON "budget" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "client_vendors_client_id_idx" ON "client_vendors" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "client_vendors_vendor_id_idx" ON "client_vendors" USING btree ("vendor_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "creative_jobs_client_id_idx" ON "creative_jobs" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_client_id_idx" ON "documents" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "events_client_id_idx" ON "events" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "floor_plans_client_id_idx" ON "floor_plans" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gifts_client_id_idx" ON "gifts" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gifts_enhanced_client_id_idx" ON "gifts_enhanced" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "messages_company_id_idx" ON "messages" USING btree ("company_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_client_id_idx" ON "payments" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "qr_codes_client_id_idx" ON "qr_codes" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "timeline_client_id_idx" ON "timeline" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "timeline_event_id_idx" ON "timeline" USING btree ("event_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vendors_company_id_idx" ON "vendors" USING btree ("company_id");