#!/usr/bin/env bash
#
# start-test-stack.sh — Isolated NON-PROD test stack for the bulletproof re-audit.
#
# Stands up a standalone local Docker stack that can NEVER bind the developer's data:
#   • Postgres  (weddingflo-test-pg)   -> host 127.0.0.1:5433, DB `weddingflo_test`
#   • Redis     (weddingflo-test-redis) -> internal only, on a dedicated network
#   • SRH       (weddingflo-test-srh)  -> host 127.0.0.1:8079  (Upstash REST bridge)
#
# Image tags are PINNED to EXACTLY match docker-compose.yml so the test stack cannot
# drift from real infra:
#   postgres:16-alpine   redis:7-alpine   hiett/serverless-redis-http:latest
# (Observation: docker-compose itself floats SRH on :latest — a drift risk flagged in
#  the audit ledger. We MATCH compose as directed rather than digest-pin here.)
#
# Rail-3 (fail-closed): this script only PROVISIONS + PRINTS PROOF. It does NOT seed or
# mutate. The seed/reset step refuses to run until the user exports TEST_DB_CONFIRMED=1.
#
# Usage:  bash scripts/start-test-stack.sh [up|down|status|proof]   (default: up)

set -euo pipefail

# --- fixed identifiers (isolated by construction) ----------------------------
NET=weddingflo-test-net
PG_NAME=weddingflo-test-pg
REDIS_NAME=weddingflo-test-redis
SRH_NAME=weddingflo-test-srh
PG_VOLUME=weddingflo_test_pgdata

PG_IMAGE=postgres:16-alpine
REDIS_IMAGE=redis:7-alpine
SRH_IMAGE=hiett/serverless-redis-http:latest

PG_HOST_PORT=5433
SRH_HOST_PORT=8079

PG_USER=postgres
PG_PASS=postgres
PG_DB=weddingflo_test   # MUST contain dev|test for the Rail-3 fail-closed name check

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.test.local"

# --- SRH token: reuse from .env.test.local if present, else generate ----------
load_or_make_srh_token() {
  if [ -f "$ENV_FILE" ] && grep -q '^UPSTASH_REDIS_REST_TOKEN=' "$ENV_FILE"; then
    SRH_TOKEN="$(grep '^UPSTASH_REDIS_REST_TOKEN=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
  else
    SRH_TOKEN="test_$(openssl rand -hex 24)"
  fi
}

up() {
  load_or_make_srh_token

  echo ">> Ensuring dedicated network: $NET"
  docker network inspect "$NET" >/dev/null 2>&1 || docker network create "$NET" >/dev/null

  echo ">> Postgres ($PG_IMAGE) on 127.0.0.1:$PG_HOST_PORT  db=$PG_DB"
  if ! docker ps -a --format '{{.Names}}' | grep -qx "$PG_NAME"; then
    docker run -d --name "$PG_NAME" --network "$NET" \
      -p 127.0.0.1:${PG_HOST_PORT}:5432 \
      -v ${PG_VOLUME}:/var/lib/postgresql/data \
      -e POSTGRES_USER=$PG_USER -e POSTGRES_PASSWORD=$PG_PASS -e POSTGRES_DB=$PG_DB \
      --health-cmd "pg_isready -U $PG_USER -d $PG_DB" \
      --health-interval 5s --health-timeout 3s --health-retries 10 \
      "$PG_IMAGE" >/dev/null
  else
    docker start "$PG_NAME" >/dev/null
  fi

  echo ">> Redis ($REDIS_IMAGE) internal-only on $NET"
  if ! docker ps -a --format '{{.Names}}' | grep -qx "$REDIS_NAME"; then
    docker run -d --name "$REDIS_NAME" --network "$NET" \
      --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 3s --health-retries 10 \
      "$REDIS_IMAGE" redis-server --appendonly no >/dev/null
  else
    docker start "$REDIS_NAME" >/dev/null
  fi

  echo ">> SRH ($SRH_IMAGE) on 127.0.0.1:$SRH_HOST_PORT -> redis://$REDIS_NAME:6379"
  if ! docker ps -a --format '{{.Names}}' | grep -qx "$SRH_NAME"; then
    docker run -d --name "$SRH_NAME" --network "$NET" \
      -p 127.0.0.1:${SRH_HOST_PORT}:80 \
      -e SRH_MODE=env -e SRH_TOKEN="$SRH_TOKEN" \
      -e SRH_CONNECTION_STRING="redis://$REDIS_NAME:6379" \
      "$SRH_IMAGE" >/dev/null
  else
    docker start "$SRH_NAME" >/dev/null
  fi

  echo ">> Waiting for Postgres health..."
  for i in $(seq 1 30); do
    status="$(docker inspect -f '{{.State.Health.Status}}' "$PG_NAME" 2>/dev/null || echo starting)"
    [ "$status" = "healthy" ] && break
    sleep 1
  done
  echo "   postgres health: $(docker inspect -f '{{.State.Health.Status}}' "$PG_NAME" 2>/dev/null)"

  write_env_file
  proof
}

write_env_file() {
  # .env.test.local is gitignored (.env*.local). Values are INERT sandbox placeholders
  # for every external side-effect SDK so a stray call can never reach a real provider.
  cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by scripts/start-test-stack.sh — gitignored test env. Do NOT commit.
# Isolated non-prod test stack (Rail 3). Side-effect keys are INERT sandbox placeholders.

# --- proven non-prod test DB (localhost / *_test) ---
DATABASE_URL=postgres://${PG_USER}:${PG_PASS}@127.0.0.1:${PG_HOST_PORT}/${PG_DB}

# --- real broadcastSync -> Redis -> SRH -> SSE chain (for true T2 perf) ---
UPSTASH_REDIS_REST_URL=http://127.0.0.1:${SRH_HOST_PORT}
UPSTASH_REDIS_REST_TOKEN=${SRH_TOKEN}

# --- external side-effects: INERT sandbox values (also stubbed via msw) ---
RESEND_API_KEY=test_inert_resend
TWILIO_ACCOUNT_SID=ACtest_inert
TWILIO_AUTH_TOKEN=test_inert_twilio
TWILIO_PHONE_NUMBER=+15005550006
STRIPE_SECRET_KEY=sk_test_inert
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_inert
FIREBASE_ADMIN_PROJECT_ID=test-inert
FIREBASE_ADMIN_CLIENT_EMAIL=test@inert.local
FIREBASE_ADMIN_PRIVATE_KEY=test_inert
R2_ENDPOINT=http://127.0.0.1:9/inert
R2_ACCESS_KEY_ID=test_inert
R2_SECRET_ACCESS_KEY=test_inert
R2_BUCKET_NAME=weddingflo-test-inert

# --- test-DB write authorization is NOT granted here. Export this yourself: ---
#   export TEST_DB_CONFIRMED=1
EOF
  echo ">> Wrote $ENV_FILE (gitignored)"
}

proof() {
  echo ""
  echo "============================================================"
  echo "RAIL-3 NON-PROD PROOF"
  echo "============================================================"
  echo "Resolved DB host : 127.0.0.1   (matches ^(localhost|127.0.0.1|.*\\.local|.*-test|.*-dev))"
  echo "Resolved DB name : ${PG_DB}     (matches /(dev|test)/  — Rail-3 token amended dev->dev|test)"
  echo "DATABASE_URL     : postgres://${PG_USER}:****@127.0.0.1:${PG_HOST_PORT}/${PG_DB}"
  echo "Redis (SRH) URL  : http://127.0.0.1:${SRH_HOST_PORT}   token=test_********"
  echo ""
  echo "Sanitized side-effect env (all INERT sandbox + msw-stubbed; audited flows hit only Redis):"
  printf "  %-26s %s\n" "RESEND_API_KEY" "test_inert_resend            (msw: api.resend.com)"
  printf "  %-26s %s\n" "TWILIO_AUTH_TOKEN" "test_inert_twilio            (msw: api.twilio.com)"
  printf "  %-26s %s\n" "STRIPE_SECRET_KEY" "sk_test_inert                (msw: api.stripe.com)"
  printf "  %-26s %s\n" "FIREBASE_ADMIN_PRIVATE_KEY" "test_inert                   (msw: fcm.googleapis.com)"
  printf "  %-26s %s\n" "R2_ENDPOINT" "http://127.0.0.1:9/inert     (msw: R2 endpoint)"
  echo ""
  echo "TEST_DB_CONFIRMED = ${TEST_DB_CONFIRMED:-<unset>}"
  if [ "${TEST_DB_CONFIRMED:-}" = "1" ]; then
    echo "GATE: OPEN — write/seed authorized."
  else
    echo "GATE: CLOSED (fail-closed). No seed/migrate/write will run."
    echo "      To authorize the proven target above:  export TEST_DB_CONFIRMED=1"
  fi
  echo "============================================================"
}

status() {
  docker ps --filter "name=weddingflo-test-" --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'
}

down() {
  echo ">> Removing test stack containers (volume ${PG_VOLUME} kept unless you 'docker volume rm' it)"
  docker rm -f "$SRH_NAME" "$REDIS_NAME" "$PG_NAME" >/dev/null 2>&1 || true
  docker network rm "$NET" >/dev/null 2>&1 || true
  echo ">> Down."
}

case "${1:-up}" in
  up) up ;;
  down) down ;;
  status) status ;;
  proof) proof ;;
  *) echo "usage: $0 [up|down|status|proof]"; exit 2 ;;
esac
